### ISSUE TITLE
Cross repo github actions

### ISSUE THREAD

**Issue by wderezin** [daringway/aws-integration#2]
https://blog.marcnuri.com/triggering-github-actions-across-different-repositories/

When push to integration on infrastructure repo, trigger this repos github action

**Comment by ksgriggs** [comment]
Notes:

```
      - name: Push infrastructure
        if: ${{ success() && github.event_name == 'repository_dispatch'}}
        run: |
          echo "This will tell infrastructure to merge into master"
```

Push repository_dispatch to create PR on module.

**Comment by wderezin** [comment]
Merged duplicate issue #13 

2 Repo:
module-repo: such as daringway/terraform-aws-infrastructure
integration-repo

Workflow

module-repo PR request to merge feature branch into integration branch
module-repo merge to integration branch
module-repo triggers integration-repo build which is the merge to master branch workflow
integration-repo runs automation job
integration-repo sends status of automation job back to module-repo (note, it is only the module-repo that triggered the build)
in module-repo:
if integration-repo job status was successful
then
merge integration branch into master
else
not sure

**Comment by ksgriggs** [comment]
Notes:

On PR  to master:
  - send repository_dispatch to aws-integration. 
    This will "terraform apply" using updated modules which have been merged into integration branch of
    terraform-aws-infrastructure.
  - wait for aws-integration to update PR with success or failure.
  - Manually merger PR if status is SUCCESS.

  I bet we can get the aws-integration workflow to update the status of the PR and not have to send 
  a return code back to terraform-aws-infrastrucure.
  Something like:  if this workflow ran because of a repository_dispatch of type "our-type-here" and is successful
  update the PR.  (Need to find out how to get the PR #.)

**Comment by wderezin** [comment]
Checkout this action: https://github.com/marketplace/actions/trigger-workflow-and-wait

In terraform-aws-infrsatructure:
On PR to master:
- send repository_dispatch to aws-integration.
  - This will "terraform apply" using updated modules which have been merged into integration branch of
terraform-aws-infrastructure.
- PR Action then waits for the dispatch (workflow) to finish

If this work it has the benefit of keeping the PR in a yellow state that the action is working.

**Comment by ksgriggs** [comment]
Workflow in terraform-aws-infrastructure has been tested and merged to master.
